import Head from "next/head";
import Image from "next/image";

import IndexNavbar from "../components/Navbar/IndexNavbar";
import IndexFooter from "../components/Footer/IndexFooter";

import html5 from "../public/html5.svg";
import css3 from "../public/css3.svg";
import javascript from "../public/javascript.svg";
import nodejs from "../public/nodejs.svg";
import reactjs from "../public/reactjs.svg";
import nextjs from "../public/nextjs.svg";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pablo Severino</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <IndexNavbar />
      <main className={styles.main}>
        <section className={styles.header}>
          <div className={styles.info}>
            <h1>Pablo Severino</h1>
            <h1>FrontEnd Developer</h1>
          </div>
          <div className={styles.Button}>
            <button className={styles.download}>Download CV</button>
            <button className={styles.contato}>Contatos</button>
          </div>
        </section>
        <section className={styles.body}>
          <div className={styles.skills}>
            <h1>Skills</h1>
            <div className={styles.left}>
              <div className={styles.html5}>
                <Image src={html5} alt="" width={64} height={64} />
                <h1>HTML5</h1>
                <span>
                  <div className={styles.nivel1}></div>
                </span>
              </div>
              <div className={styles.css3}>
                <Image src={css3} alt="" width={64} height={64} />
                <h1>CSS3</h1>
                <span>
                  <div className={styles.nivel2}></div>
                </span>
              </div>
              <div className={styles.javascript}>
                <Image src={javascript} alt="" width={64} height={64} />
                <h1>JavaScript</h1>
                <span>
                  <div className={styles.nivel3}></div>
                </span>
              </div>
            </div>
            <div className={styles.right}>
              <div className={styles.nodejs}>
                <Image src={nodejs} alt="" width={64} height={64} />
                <h1>Node JS</h1>
                <span>
                  <div className={styles.nivel4}></div>
                </span>
              </div>
              <div className={styles.reactjs}>
                <Image src={reactjs} alt="" width={64} height={64} />
                <h1>React JS</h1>
                <span>
                  <div className={styles.nivel5}></div>
                </span>
              </div>
              <div className={styles.nextjs}>
                <Image src={nextjs} alt="" width={64} height={64} />
                <h1>Next JS</h1>
                <span>
                  <div className={styles.nivel6}></div>
                </span>
              </div>
            </div>
          </div>
          <div className={styles.projects}>
            <h1>Projects</h1>
            <div className={styles.logos}> 
              <div className={styles.stackbitz}>
                <Image src="../stackbitz-ui.svg" alt="" width={180} height={180} />
                <h1>StackBitz UI</h1>
              </div>
              <div className={styles.sakai}>
                <Image src="../sakai-ui.svg" alt="" width={180} height={180} />
                <h1>Sakai UI</h1>
              </div>
              <div className={styles.rocketstar}>
                <Image src="../rocketstar.svg" alt="" width={180} height={180} />
                <h1>Rocketstar</h1>
              </div>
            </div>
          </div>
          <div className={styles.about}>
            <h1>About</h1>
          </div>
          <div className={styles.contacts}>
            <h1>Contacts</h1>
            <form>
              <div className={styles.name}>
                <label>Name</label>
                <input type="text" />
              </div>
              <div className={styles.email}>
                <label>Email</label>
                <input type="email" />
              </div>
              <div className={styles.message}>
                <label>Message</label>
                <input type="text" />
              </div>
              <button type="submit">Submit</button>
            </form>
          </div>
        </section>
      </main>
      <IndexFooter />
    </>
  )
}
