import Head from "next/head";
import Image from "next/image";

import IndexNavbar from "../components/Navbar/IndexNavbar";
import IndexFooter from "../components/Footer/IndexFooter";

import html5 from "../public/html5.svg";
import css3 from "../public/css3.svg";
import javascript from "../public/javascript.svg";
import nodejs from "../public/nodejs.svg";
import reactjs from "../public/reactjs.svg";
import nextjs from "../public/nextjs.svg";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IndexNavbar />
      <main className={styles.main}>
        <section className={styles.header}>
          <button>Download CV</button>
          <button>Contatos</button>
          <p>Aliqua amet Lorem veniam proident dolor non veniam dolor et ad consectetur reprehenderit ipsum qui. Consequat id Lorem pariatur duis deserunt ex labore in culpa duis aliquip velit cillum. Laborum ullamco laborum consequat non sint mollit et occaecat. Lorem reprehenderit pariatur excepteur laborum magna proident et elit dolor minim.</p>
        </section>
        <section className={styles.body}>
          <Image src={html5} alt="" />
          <Image src={css3} alt="" />
          <Image src={javascript} alt="" />
          <Image src={nodejs} alt="" />
          <Image src={reactjs} alt="" />
          <Image src={nextjs} alt="" />
        </section>
      </main>
      <IndexFooter />
    </>
  )
}
