import Head from 'next/head'
import Image from 'next/image'

import IndexNavbar from '@/components/Navbar/IndexNavbar'
import IndexHeader from '@/components/Header/IndexHeader'

import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Pablo Severino</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <IndexNavbar />
      <main className={styles.main}>
        <IndexHeader />
      </main>
    </>
  )
}
